# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0006_auto_20160719_0736'),
        ('usermodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermoduleprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='usermoduleprofile',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='usermoduleprofile',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_role', to='usermodule.OrganizationRole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermoduleprofile',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='usermoduleprofile',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_branch', to='project_data.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermoduleprofile',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermoduleprofile',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
