# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0002_auto_20160719_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermoduleprofile',
            name='position',
        ),
    ]
