# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0003_remove_usermoduleprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleprofile',
            name='security_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
