# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0007_auto_20160721_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrole',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
