# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0008_organizationrole_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRolePermissionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskname_role_map', to='usermodule.OrganizationRole')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taskrolepermissionmap',
            unique_together=set([('name', 'role')]),
        ),
    ]
