# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0009_auto_20160801_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='taskrolepermissionmap',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskname_map', to='usermodule.Task'),
        ),
        migrations.AlterField(
            model_name='taskrolepermissionmap',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskrole_map', to='usermodule.OrganizationRole'),
        ),
    ]
