# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_date_time', models.DateTimeField()),
                ('transaction_amount', models.CharField(max_length=100)),
                ('remarks_of_csa_customer', models.CharField(max_length=400)),
                ('remarks_of_bkash_cs', models.CharField(max_length=400)),
                ('execution_status', models.CharField(max_length=100)),
                ('not_execute_reason', models.CharField(max_length=100)),
            ],
        ),
    ]
