# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0003_complain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[(b'active', b'Active'), (b'deactive', b'Deactive')], max_length=10)),
            ],
        ),
    ]
