# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0004_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='execution_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='not_execute_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='remarks_of_bkash_cs',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
