# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0005_auto_20160719_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='account_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='balance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='id_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='id_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='remarks_of_csa_customer',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='service_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='transaction_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='transaction_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
