# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_data', '0006_auto_20160719_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='pin',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='user_pin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complain',
            name='not_execute_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='remarks_of_bkash_cs',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
