# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0008_complainstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='received_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complainstatuslog',
            name='change_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
