# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='received_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
