# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_data', '0011_complain_received_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='locker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[(b'', b'Select a Status'), (b'active', b'Active'), (b'deactive', b'Deactive')], max_length=10),
        ),
    ]
